import {create} from 'zustand'; import {workflows as seed} from '../../mock-data/workflows'; import {instances} from '../../mock-data/instances'; import {roles} from '../../mock-data/catalog'; import type {FlowEdge,FlowNode,SensitiveAudit,ValidationIssue,Workflow} from '../types'; import {auditTime,getFormFields,getGrants,isSensitiveField} from '../utils/sensitive';
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const validate=(w:Workflow):ValidationIssue[]=>{const issues:ValidationIssue[]=[]; if(!w.nodes.some(n=>n.type==='end')) issues.push({nodeId:w.nodes[0]?.id||'flow',level:'error',message:'流程缺少结束节点'}); const linked=new Set(w.edges.flatMap(e=>[e.source,e.target])); w.nodes.filter(n=>n.type!=='start'&&n.type!=='end'&&!linked.has(n.id)).forEach(n=>issues.push({nodeId:n.id,level:'error',message:'必经节点不能孤立'})); w.nodes.forEach(n=>{if(n.type==='condition'&&!n.data.config.ruleType)issues.push({nodeId:n.id,level:'error',message:'条件分支规则未配置'}); if(n.type==='approval'&&!n.data.config.approverSource)issues.push({nodeId:n.id,level:'error',message:'审批人不能为空'});});
 // 敏感字段发布校验：授权缺角色 / 引用已删字段一律拦截发布，并指出节点与字段
 const fields=getFormFields(w.nodes); const fieldMap=new Map(fields.map(f=>[f.id,f])); const approvals=w.nodes.filter(n=>n.type==='approval');
 const granted=new Set<string>();
 approvals.forEach(node=>getGrants(node).forEach(g=>{const field=fieldMap.get(g.fieldId);
  if(!field){issues.push({nodeId:node.id,level:'error',message:`敏感字段授权引用了已删除字段（字段 ID：${g.fieldId}）`});return}
  if(!g.roles.length){issues.push({nodeId:node.id,level:'error',message:`敏感字段「${field.label}」未指定可查看原文的角色`});return}
  granted.add(g.fieldId);
 }));
 // 敏感字段在整个流程没有任何有效授权
 const firstApproval=approvals[0];
 fields.filter(isSensitiveField).forEach(f=>{if(!granted.has(f.id))issues.push({nodeId:firstApproval?.id??'flow',level:'error',message:`敏感字段「${f.label}」未配置任何可查看原文的审批角色`})});
 return issues};
interface State{workflows:Workflow[];instances:typeof instances;currentId:string;selectedNodeId:string|null;issues:ValidationIssue[];toast:string;viewRole:string;audits:SensitiveAudit[];setCurrent:(id:string)=>void;selectNode:(id:string|null)=>void;setViewRole:(role:string)=>void;updateNodes:(nodes:FlowNode[])=>void;updateEdges:(edges:FlowEdge[])=>void;updateConfig:(id:string,config:Record<string,any>)=>void;runValidation:()=>ValidationIssue[];save:()=>void;publish:()=>void;create:()=>string;copy:(id:string)=>void;archive:(id:string)=>void;restore:(v:number)=>void;recordSensitiveView:(a:Omit<SensitiveAudit,'id'|'time'>)=>SensitiveAudit;clearToast:()=>void}
export const useAppStore=create<State>((set,get)=>({workflows:clone(seed),instances,currentId:'wf-1',selectedNodeId:null,issues:[],toast:'',viewRole:roles[1]/*部门负责人*/,audits:[],setCurrent:id=>set({currentId:id,selectedNodeId:null,issues:[]}),selectNode:id=>set({selectedNodeId:id}),setViewRole:role=>set({viewRole:role}),updateNodes:nodes=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes}:w)})),updateEdges:edges=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,edges}:w)})),updateConfig:(id,config)=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes:w.nodes.map(n=>n.id===id?{...n,data:{...n.data,config:{...n.data.config,...config},state:'configuring'}}:n)}:w)})),runValidation:()=>{const w=get().workflows.find(x=>x.id===get().currentId)!; const issues=validate(w); set(s=>({issues,workflows:s.workflows.map(x=>x.id===w.id?{...x,nodes:x.nodes.map(n=>({...n,data:{...n.data,state:issues.some(i=>i.nodeId===n.id)?'invalid':'valid'}}))}:x),toast:issues.some(i=>i.level==='error')?`发现 ${issues.length} 个问题，已拦截发布`:'校验通过'}));return issues},save:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'draft',updatedAt:'2026-07-11 16:30'}:w),toast:'草稿已保存'})),publish:()=>{const current=get().workflows.find(x=>x.id===get().currentId)!;const blockers=validate(current).filter(i=>i.level==='error');if(blockers.length){set({issues:blockers,toast:`存在 ${blockers.length} 个阻断项，无法发布`});return}set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'published',version:w.version+1,publishedAt:'2026-07-11 16:35',updatedAt:'2026-07-11 16:35',versions:[...w.versions,{version:w.version+1,createdAt:'2026-07-11 16:35',note:'发布最新审批配置',nodes:clone(w.nodes),edges:clone(w.edges)}]}:w),toast:'流程发布成功'}))},create:()=>{const id='wf-'+Date.now();set(s=>({workflows:[{id,name:'未命名流程',domain:'财务',status:'draft',version:0,editor:'林秋',updatedAt:'2026-07-11 16:40',abnormalCount:0,nodes:[],edges:[],versions:[]},...s.workflows],currentId:id}));return id},copy:id=>set(s=>{const w=s.workflows.find(x=>x.id===id)!;return{workflows:[{...clone(w),id:'wf-'+Date.now(),name:w.name+'（副本）',status:'draft'},...s.workflows]}}),archive:id=>set(s=>({workflows:s.workflows.map(w=>w.id===id?{...w,status:'archived'}:w)})),restore:v=>set(s=>({workflows:s.workflows.map(w=>{if(w.id!==s.currentId)return w;const old=w.versions.find(x=>x.version===v)!;return{...w,status:'draft',nodes:clone(old.nodes),edges:clone(old.edges)}}),toast:`已恢复 v${v} 为草稿`})),recordSensitiveView:a=>{const audit:SensitiveAudit={...a,id:'aud-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),time:auditTime()};set(s=>({audits:[...s.audits,audit]}));return audit},clearToast:()=>set({toast:''})}));
