import {useEffect,useMemo,useState} from 'react';import {useSearchParams} from 'react-router-dom';import {Activity,AlertTriangle,Clock,Download,FileKey,Search,ShieldCheck,X} from 'lucide-react';import {Empty,PageTitle,Status} from '../components/common';import {FlowCanvas} from '../components/FlowCanvas';import {SensitiveFieldRow} from '../components/SensitiveFieldRow';
import {useAppStore} from '../store/useAppStore';
import {exportCsv,getFormFields,isSensitiveField,maskValue} from '../utils/sensitive';
import type {FormField} from '../types';
export function Monitor(){const ins=useAppStore(s=>s.instances),ws=useAppStore(s=>s.workflows),viewRole=useAppStore(s=>s.viewRole),audits=useAppStore(s=>s.audits),record=useAppStore(s=>s.recordSensitiveView),setToast=(t:string)=>useAppStore.setState({toast:t});const [params]=useSearchParams();const [filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(params.get('instance'));
 // 已揭示字段集合：切角色 / 切实例时全部清空，绝不沿用旧明文
 const [revealed,setRevealed]=useState<Set<string>>(new Set());
 const selectInstance=(id:string|null)=>{setSelected(id);setRevealed(new Set())};
 // 全局头部切换角色时同样重置已揭示明文，杜绝跨角色沿用
 useEffect(()=>{setRevealed(new Set())},[viewRole]);
 const rows=useMemo(()=>ins.filter(i=>filter==='all'||i.status===filter),[ins,filter]);const item=ins.find(i=>i.id===selected),flow=ws.find(w=>w.id===item?.workflowId);
 const fields=flow?getFormFields(flow.nodes):[];const approval=flow?.nodes.find(n=>n.type==='approval');const currentApproval=flow?.nodes.find(n=>n.data.label===item?.currentNode&&n.type==='approval')??approval;
 const itemAudits=useMemo(()=>item?audits.filter(a=>a.instanceId===item.id):[],[audits,item]);
 const shownFor=(f:FormField):string=>{const raw=item?.formData?.[f.id]??'';if(!isSensitiveField(f))return raw||'—';return revealed.has(f.id)?raw||'—':maskValue(raw,f.type)||'—'};
 const reveal=(f:FormField)=>{if(!item||!currentApproval)return;record({instanceId:item.id,fieldId:f.id,fieldLabel:f.label,nodeId:currentApproval.id,nodeLabel:currentApproval.data.label,role:viewRole});setRevealed(prev=>new Set(prev).add(f.id))};
 const visibleRows=item&&flow?fields.map(f=>({field:f,shown:shownFor(f)})):[];
 return <div className="page"><PageTitle eyebrow="运行中心" title="Runtime Monitor" desc="观察流程实例状态、耗时和风险，快速定位异常节点。敏感字段按当前查看角色重算。"/><section className="monitor-kpis">{[['运行中',ins.filter(i=>i.status==='running').length,Activity],['异常',ins.filter(i=>i.status==='abnormal').length,AlertTriangle],['超时',ins.filter(i=>i.status==='timeout').length,Clock],['今日完成',ins.filter(i=>i.status==='completed').length,Activity]].map(([a,b,I]:any)=><article key={a}><I/><span><small>{a}</small><b>{b}</b></span></article>)}</section><div className="toolbar panel"><div className="search"><Search/><input placeholder="搜索实例或申请人"/></div>{[['all','全部'],['abnormal','异常'],['timeout','超时'],['running','进行中'],['completed','完成']].map(([v,l])=><button key={v} className={'filter '+(filter===v?'active':'')} onClick={()=>setFilter(v)}>{l}</button>)}</div><section className="panel monitor-table"><table><thead><tr><th>实例编号</th><th>申请人</th><th>业务域</th><th>当前节点</th><th>状态</th><th>提交时间</th><th>耗时</th><th>风险</th></tr></thead><tbody>{rows.map(i=><tr key={i.id} data-testid="instance-row" onClick={()=>selectInstance(i.id)}><td><b>{i.id}</b></td><td>{i.applicant}</td><td>{i.domain}</td><td>{i.currentNode}</td><td><Status value={i.status}/></td><td>{i.submittedAt}</td><td>{i.duration}</td><td><Status value={i.risk}/></td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</section>{item&&flow&&<div className="drawer-backdrop"><aside className="instance-drawer" data-testid="instance-detail"><div className="drawer-head"><div><small>流程实例详情</small><h2>{item.id}</h2></div><button className="icon-btn" onClick={()=>selectInstance(null)}><X/></button></div><div className="detail-meta"><div><small>申请人</small><b>{item.applicant}</b></div><div><small>状态</small><Status value={item.status}/></div><div><small>耗时</small><b>{item.duration}</b></div><div><small>风险</small><Status value={item.risk}/></div></div>
 <div className="drawer-role" data-testid="drawer-role"><ShieldCheck/><span>查看角色：<b>{viewRole}</b></span><small>敏感字段按该角色在「{currentApproval?.data.label??'审批节点'}」的授权重算</small></div>

 <h3>表单数据</h3>{fields.length?<div className="instance-data panel" data-testid="instance-data">{fields.map(f=>{const raw=item.formData?.[f.id]??'';return isSensitiveField(f)?<div key={f.id} className="data-row sensitive" data-testid={'data-row-'+f.id}><div className="p-field-label"><b>{f.label}</b><small>敏感</small></div><SensitiveFieldRow field={f} raw={raw} node={currentApproval} instanceId={item.id} revealed={revealed.has(f.id)} onReveal={()=>reveal(f)} onHide={()=>setRevealed(prev=>{const next=new Set(prev);next.delete(f.id);return next})}/></div>:<div key={f.id} className="data-row"><div className="p-field-label"><b>{f.label}</b><small>普通</small></div><div className="p-field-val">{raw||'—'}</div></div>})}<div className="instance-data-actions"><button type="button" data-testid="instance-export" onClick={()=>{exportCsv(`${item.id}-${viewRole}.csv`,visibleRows.map(r=>({label:r.field.label,value:r.shown})));setToast('已导出 CSV：未授权或未揭示的敏感字段为遮罩')}}><Download/>导出可见数据</button></div></div>:<p className="config-hint">该流程没有表单字段。</p>}

 <h3><FileKey className="h4-icon"/>敏感字段查看记录</h3><div className="audit-box panel" data-testid="audit-box"><div className="audit-head"><span>本实例累计查看 <b data-testid="audit-count">{itemAudits.length}</b> 次</span><small>按角色、节点、字段与时间逐次留痕，不可随角色切换复用</small></div>{itemAudits.length?<table className="audit-table"><thead><tr><th>时间</th><th>角色</th><th>节点</th><th>字段</th></tr></thead><tbody>{itemAudits.map(a=><tr key={a.id} data-testid="audit-row"><td>{a.time}</td><td>{a.role}</td><td>{a.nodeLabel}</td><td>{a.fieldLabel}</td></tr>)}</tbody></table>:<Empty title="暂无查看记录" text="授权角色点击“查看原文”后会在这里按次累计。"/>}</div>

 <h3>执行流程</h3><div className="runtime-canvas"><FlowCanvas nodes={flow.nodes} edges={flow.edges} onNodes={()=>{}} onEdges={()=>{}} onSelect={()=>{}} highlight={flow.nodes.find(n=>n.data.label===item.currentNode)?.id}/></div><h3>执行时间线</h3><div className="timeline" data-testid="execution-timeline">{item.timeline.map(t=><div key={t.title} className={t.status}><i/><span><b>{t.title}</b><small>{t.time}</small></span><Status value={t.status}/></div>)}</div></aside></div>}</div>}
