import {useEffect,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {ArrowLeft,Copy,Download,Paperclip,RotateCcw,ShieldCheck} from 'lucide-react';import {useAppStore} from '../store/useAppStore';
import {SensitiveFieldRow} from '../components/SensitiveFieldRow';
import type {FormField} from '../types';
import {exportCsv,getFormFields,isSensitiveField,maskValue} from '../utils/sensitive';
export function Preview(){const nav=useNavigate(),{id}=useParams(),w=useAppStore(s=>s.workflows.find(x=>x.id===id))!;const viewRole=useAppStore(s=>s.viewRole),record=useAppStore(s=>s.recordSensitiveView),setToast=(t:string)=>useAppStore.setState({toast:t});const form=w.nodes.find(n=>n.type==='form'),condition=w.nodes.find(n=>n.type==='condition');const fields:FormField[]=getFormFields(w.nodes);const approvals=w.nodes.filter(n=>n.type==='approval');const [values,setValues]=useState<Record<string,string>>({});const [nodeId,setNodeId]=useState(approvals[0]?.id??'');const [revealed,setRevealed]=useState<Set<string>>(new Set());
 // 切角色 / 切节点 / 切流程：已揭示明文全部清空，不能沿用旧结果
 useEffect(()=>{setNodeId(approvals[0]?.id??'')},[w.id]);
 useEffect(()=>{setRevealed(new Set())},[viewRole,nodeId,w.id]);
 const amount=Number(values.amount||0),threshold=Number(condition?.data.config.value||5000),branch=amount>threshold?'高额分支：通知财务审批人':'标准分支：写入系统记录';const [submitted,setSubmitted]=useState(false);
 const node=w.nodes.find(n=>n.id===nodeId);
 // 屏幕显示与复制/导出共用同一口径：敏感字段只有“已点击揭示并留痕”才是原文
 const shownFor=(f:FormField)=>{const raw=values[f.id]??'';if(!isSensitiveField(f))return raw||'—';return revealed.has(f.id)?raw||'—':maskValue(raw,f.type)||'—'};
 const visibleRows=fields.map(f=>({field:f,shown:shownFor(f)}));
 const reveal=(f:FormField)=>{record({instanceId:`preview-${w.id}`,fieldId:f.id,fieldLabel:f.label,nodeId:node?.id??'flow',nodeLabel:node?.data.label??'流程',role:viewRole});setRevealed(prev=>new Set(prev).add(f.id))};
 const copyAll=async()=>{const text=visibleRows.map(r=>`${r.field.label}：${r.shown}`).join('\n');await navigator.clipboard?.writeText(text).catch(()=>{});setToast('已复制当前可见内容（未揭示的敏感字段为遮罩）')};
 return <div className="preview-page"><header className="preview-header"><button className="icon-btn" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/></button><div><b>表单预览</b><small>{w.name} · 实时分支模拟</small></div><span className="spacer"/><button className="secondary" onClick={()=>setValues({})}><RotateCcw/>重置</button><button onClick={()=>setSubmitted(true)}>模拟提交</button></header><div className="preview-stage"><section className="form-preview"><div className="form-cover"><small>{w.domain} / 申请表单</small><h1>{form?.data.label||'业务申请'}</h1><p>请完整填写以下信息，带 * 的字段为必填项。</p></div><div className="form-body">{(form?.data.config.fields||[]).map((f:FormField)=><label key={f.id}>{f.label}{f.required&&<em>*</em>}{f.type==='attachment'?<div className="upload"><Paperclip/><b>拖入文件或点击上传</b><small>支持 PDF、DOCX、PNG，单个文件不超过 20MB</small></div>:f.type==='text'?<textarea aria-label={f.label} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} rows={5} placeholder="请输入详细说明（最多 2,000 字）"/>:<div className={f.type==='amount'?'money-input':''}>{f.type==='amount'&&<span>¥</span>}<input aria-label={f.label} type={f.type==='amount'||f.type==='number'?'number':f.type==='date'?'date':f.type==='phone'?'tel':'text'} inputMode={f.type==='bankcard'?'numeric':undefined} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} placeholder={f.type==='amount'?'0.00':f.type==='phone'?'请输入 11 位手机号':f.type==='bankcard'?'请输入银行卡号':'请输入'}/></div>}{submitted&&f.required&&!values[f.id]&&<small className="field-error">此字段为必填项</small>}</label>)}</div></section>
 <aside className="simulation"><h3>条件分支模拟</h3><p>表单字段变化会实时计算流程走向。</p><div className="sim-rule"><small>当前规则</small><b>申请金额 &gt; ¥{threshold.toLocaleString()}</b></div><div className={'sim-result '+(amount>threshold?'high':'normal')} data-testid="branch-result"><small>模拟结果</small><b>{branch}</b><p>当前输入：¥{amount.toLocaleString(undefined,{minimumFractionDigits:2})}</p></div><div className="sim-path"><span className="done">提交申请</span><i>↓</i><span className="done">直属主管审批</span><i>↓</i><span className="active">{amount>threshold?'高额通知':'记录系统'}</span></div></aside>

 <section className="perspective panel" data-testid="approval-perspective"><div className="perspective-head"><ShieldCheck/><div><h3>审批视角 · 字段可见性</h3><small>按“查看角色 + 审批节点”即时重算；只有点击“查看原文”并留痕后，复制与导出才包含明文；切换角色或节点不会沿用旧结果。</small></div></div><div className="perspective-controls"><label>审批节点<select aria-label="审批节点视角" data-testid="perspective-node" value={nodeId} onChange={e=>setNodeId(e.target.value)}>{approvals.map(n=><option key={n.id} value={n.id}>{n.data.label}</option>)}</select></label><div className="perspective-role"><small>当前查看角色</small><b data-testid="perspective-role">{viewRole}</b></div></div>{fields.length===0?<p className="config-hint">该流程还没有表单字段。</p>:<div className="perspective-fields">{fields.map(f=>{const raw=values[f.id]??'';if(isSensitiveField(f)){return <div key={f.id} className="p-field sensitive" data-testid={'p-field-'+f.id}><div className="p-field-label"><b>{f.label}</b><small>敏感</small></div><SensitiveFieldRow field={f} raw={raw} node={node} instanceId={`preview-${w.id}`} revealed={revealed.has(f.id)} onReveal={()=>reveal(f)} onHide={()=>setRevealed(prev=>{const next=new Set(prev);next.delete(f.id);return next})}/></div>}return <div key={f.id} className="p-field" data-testid={'p-field-'+f.id}><div className="p-field-label"><b>{f.label}</b><small>普通</small></div><div className="p-field-val">{raw||'—'}</div></div>})}</div>}<div className="perspective-actions"><button type="button" className="secondary" data-testid="perspective-copy" onClick={copyAll}><Copy/>复制可见内容</button><button type="button" data-testid="perspective-export" onClick={()=>{exportCsv(`${w.name}-${viewRole}-${node?.data.label??''}.csv`,visibleRows.map(r=>({label:r.field.label,value:r.shown})));setToast('已导出 CSV：仅包含当前角色已可见/已揭示的内容')}}><Download/>导出 CSV</button></div>{!approvals.length&&<small className="no-perm">流程中暂无审批节点。</small>}<div className="mask-demo"><small>未揭示内容示例：{fields.filter(isSensitiveField).map(f=>maskValue(values[f.id]||'13800000000',f.type)).filter(Boolean).join('、')||'（无敏感字段）'}</small></div></section>
 </div></div>}
